import default_image from '../../images/default_image.png';

export const map = [
	["userimage","userimage",default_image],
	["realname_checkbox","username.show"],
	["realname","username.data"],
	["nickname_checkbox","nickname.show"],
	["nickname","nickname.data"],
	["shortintro","profile.data"],
	["email_checkbox","profile.show"],
	["email","publicEmail.data"],
	["phone_company_checkbox","office.show"],
	["phone_company","office.data"],
	["phone_home_checkbox","homephone.show"],
	['phone_home','homephone.data'],
	['mobile_checkbox','cellphone.show'],
	['mobile','cellphone.data'],
	['address_checkbox','CC.show'],
	['address','CC.data'],
	['personal_website_checkbox','web.show'],
	['personal_website','web.data'],
	['facebook_checkbox','facebook.show'],
	['facebook','facebook.data'],
	['Linkedin_checkbox','Linkedin.show'],
	['Linkedin','Linkedin.data'],
	['major_checkbox','education.major.show'],
	['major','education.major.SD'],
	['double_major_checkbox','education.double_major.show'],
	['double_major','education.double_major.SD'],
	['minor_checkbox','education.minor.show'],
	['minor','education.minor.SD'],
	['master_checkbox','education.master.show'],
	['master','education.master.SD'],
	['doctor_checkbox','education.doctor.show'],
	['doctor','education.doctor.SD'],
]